### PR TITLE
Initial gitops install of chains plus simple demo

### PR DESCRIPTION
**Pull request by simonbaird**
Includes:
* Gitops config to install chains
* A script to help create a signing secret
* Scripts to help configure CA certs to get SSL working for chains
* Scripts to help demo chains, cosign and rekor-cli with a simple kaniko build task

Caveats/Todo:
* It doesn't work smoothly in a cluster-bot cluster
* There are some scripts you need to run after the gitops sync is done
* The demo uses the internal image registry rather than quay.io
* Demo doesn't cover S2I or Buildah builds

All these things can be addressed later - they're not considered blockers for merging this into the contract-devel branch.

Jiras:
* [HACBS-38](https://issues.redhat.com/browse/HACBS-38)
* [HACBS-47](https://issues.redhat.com/browse/HACBS-47)

### CODE REVIEW

**Comment by simonbaird** [comment]
This is a newer version of https://github.com/redhat-appstudio/infra-deployments/pull/111 .

To facilitate collaboration within the Enterprise Contract team, the plan is to review and merge PRs into a branch called 'contract-devel'. We can then pull that down locally and build things on top of it. Eventually there will be a PR to merge the contract-devel branch into the main branch in the main repo.

**Comment by simonbaird** [comment]
FYI @hacbs-contract/devs

**Comment by simonbaird** [comment]
Replaces https://github.com/redhat-appstudio/infra-deployments/pull/111 .

**Comment by simonbaird** [comment]
I just want to double check it still works for me before moving out of draft mode. I got a failure just now, but I didn't check if Argo CD was finished syncing, so I'm going to try it again.

**Comment by simonbaird** [comment]
Okay, still working afaict.

**Comment by caugello** [comment]
LGTM

**Comment by joejstuart** [comment]
LGTM

**Comment by simonbaird** [comment]
Thanks, let's merge.

**Pull request merged**
